/// Provides simple localization without relying on intl packages.
class AppLocalizations {
  final String languageCode;
  AppLocalizations(this.languageCode);

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'select_language': 'Select Language',
      'continue': 'Continue',
      'no_language_selected': 'No Language Selected',
      'please_select_language': 'Please select a language to continue.',
      'change_language': 'Change Language',
      'legal': 'Legal',
      'about_us': 'About Us',
      'privacy_policy': 'Privacy Policy',
      'terms_of_service': 'Terms of Service',
      'contact': 'Contact',
      'contact_us': 'Contact Us',
      'preferences': 'Preferences',
      'settings': 'Settings',
      'forget_saved_number': 'Forget Saved Number',
      'are_you_sure': 'Are you sure?',
      'remove_saved_number': 'This will remove the saved number from your device.',
      'cancel': 'Cancel',
      'forget': 'Forget',
      'saved_number_forgotten': 'Saved number has been forgotten.',
      'share_app': 'Share App',
      'app_theme': 'App Theme',
      'system_default': 'System Default',
      'light_mode': 'Light Mode',
      'dark_mode': 'Dark Mode',
      'select_theme': 'Select Theme',
      'track': 'Track',
      'booking': 'Booking',
      'history': 'History',
      'coming_soon': 'Coming Soon',
      'profile': 'Profile',
      'track_your_luggage': 'TRACK YOUR LUGGAGE',
      'enter_phone_and_code': '* Enter phone number and cargo number as appeared on the receipt',
      'sender_receiver_number': '(sender or receiver number)',
      'please_enter_phone_number': 'Please enter a phone number',
      'code_number': 'Code number',
      'please_enter_tracking_code': 'Please enter the tracking code',
      'save_number_question': 'Save Number?',
      'would_you_like_to_save_number': 'Would you like to save this phone number for next time?',
      'dont_save': "Don't Save",
      'save': 'Save',
      'checking_package': 'Checking your package...',
      'no_cargo_found': 'No cargo found',
      'quick_check': 'Quick check',
      'cargo_details': 'Cargo Details',
      'out': 'out',
      'store': 'store',
      'dispatch_info': 'Dispatch Info',
      'dispatch_date': 'Dispatch Date',
      'dispatch_status': 'Dispatch Status',
      'cargo_id': 'Cargo ID',
      'cargo_info': 'Cargo Info',
      'registered': 'Registered',
      'sender': 'Sender',
      'receiver': 'Receiver',
      'quantity': 'Quantity',
      'payment_option': 'Payment Option',
      'total_price': 'Total Price',
      'tracking_history': 'Tracking History',
      'status': 'Status',
    },
    'sw': {
      'select_language': 'Chagua Lugha',
      'continue': 'Endelea',
      'no_language_selected': 'Hakuna Lugha Imechaguliwa',
      'please_select_language': 'Tafadhali chagua lugha kuendelea.',
      'change_language': 'Badilisha Lugha',
      'legal': 'Kisheria',
      'about_us': 'Kuhusu Sisi',
      'privacy_policy': 'Sera ya Faragha',
      'terms_of_service': 'Sheria na Masharti',
      'contact': 'Mawasiliano',
      'contact_us': 'Wasiliana Nasi',
      'preferences': 'Mapendeleo',
      'settings': 'Mipangilio',
      'forget_saved_number': 'Sahau Nambari Iliyohifadhiwa',
      'are_you_sure': 'Una uhakika?',
      'remove_saved_number': 'Hii itaondoa nambari iliyohifadhiwa kwenye kifaa chako.',
      'cancel': 'Ghairi',
      'forget': 'Sahau',
      'saved_number_forgotten': 'Nambari iliyohifadhiwa imesahaulika.',
      'share_app': 'Shiriki Programu',
      'app_theme': 'Mandhari ya Programu',
      'system_default': 'Mfumo Chaguomsingi',
      'light_mode': 'Mwanga',
      'dark_mode': 'Giza',
      'select_theme': 'Chagua Mandhari',
      'track': 'Fuata',
      'booking': 'Booking',
      'history': 'Historia',
      'coming_soon': 'Inakuja Hivi Karibuni',
      'profile': 'Wasifu',
      'track_your_luggage': 'Fuatilia Mizigo Yako',
      'enter_phone_and_code': '* Ingiza nambari ya simu na nambari ya mzigo kama ilivyo kwenye risiti',
      'sender_receiver_number': '(namba ya mtumaji au mpokeaji)',
      'please_enter_phone_number': 'Tafadhali ingiza nambari ya simu',
      'code_number': 'Nambari ya mzigo',
      'please_enter_tracking_code': 'Tafadhali ingiza nambari ya ufuatiliaji',
      'save_number_question': 'Hifadhi Namba?',
      'would_you_like_to_save_number': 'Je, ungependa kuhifadhi namba hii kwa matumizi yajayo?',
      'dont_save': 'Usihifadhi',
      'save': 'Hifadhi',
      'checking_package': 'Inaangalia kifurushi chako...',
      'no_cargo_found': 'Hakuna mzigo uliopatikana',
      'quick_check': 'Angalia haraka',
      'cargo_details': 'Maelezo ya Mizigo',
      'out': 'nje',
      'store': 'ghalani',
      'dispatch_info': 'Taarifa za Usafirishaji',
      'dispatch_date': 'Tarehe ya Usafirishaji',
      'dispatch_status': 'Hali ya Usafirishaji',
      'cargo_id': 'Kitambulisho cha mzigo',
      'cargo_info': 'Taarifa za Mizigo',
      'registered': 'Imesajiliwa',
      'sender': 'Mtumaji',
      'receiver': 'Mpokeaji',
      'quantity': 'Kiasi',
      'payment_option': 'Njia ya Malipo',
      'total_price': 'Jumla ya Bei',
      'tracking_history': 'Historia ya Ufuatiliaji',
      'status': 'Hali',
    },
    'fr': {
      'select_language': 'Choisir la langue',
      'continue': 'Continuer',
      'no_language_selected': 'Aucune langue sélectionnée',
      'please_select_language': 'Veuillez sélectionner une langue pour continuer.',
      'change_language': 'Changer de langue',
      'legal': 'Juridique',
      'about_us': 'À propos de nous',
      'privacy_policy': 'Politique de confidentialité',
      'terms_of_service': "Conditions d'utilisation",
      'contact': 'Contact',
      'contact_us': 'Contactez-nous',
      'preferences': 'Préférences',
      'settings': 'Paramètres',
      'forget_saved_number': 'Oublier le numéro enregistré',
      'are_you_sure': 'Êtes-vous sûr?',
      'remove_saved_number': "Cela supprimera le numéro enregistré de votre appareil.",
      'cancel': 'Annuler',
      'forget': 'Oublier',
      'saved_number_forgotten': 'Le numéro enregistré a été oublié.',
      'share_app': "Partager l'application", 
      'app_theme': "Thème de l'application", 
      'system_default': 'Système par défaut',
      'light_mode': 'Clair',
      'dark_mode': 'Sombre',
      'select_theme': 'Sélectionner le thème',
      'track': 'Suivre',
      'booking': 'Réservation',
      'history': 'Historique',
      'coming_soon': 'Bientôt disponible',
      'profile': 'Profil',
      'track_your_luggage': 'SUIVEZ VOS BAGAGES',
      'enter_phone_and_code': "* Entrez le numéro de téléphone et le numéro du colis tels qu'indiqués sur le reçu",
      'sender_receiver_number': "(numéro de l'expéditeur ou du destinataire)",
      'please_enter_phone_number': 'Veuillez entrer un numéro de téléphone',
      'code_number': 'Numéro de code',
      'please_enter_tracking_code': 'Veuillez entrer le code de suivi',
      'save_number_question': 'Enregistrer le numéro ?',
      'would_you_like_to_save_number': 'Souhaitez-vous enregistrer ce numéro pour la prochaine fois ?',
      'dont_save': 'Ne pas enregistrer',
      'save': 'Enregistrer',
      'checking_package': 'Vérification de votre colis...',
      'no_cargo_found': 'Aucun colis trouvé',
      'quick_check': 'Vérification rapide',
      'cargo_details': 'Détails du colis',
      'out': 'sorti',
      'store': 'entrepôt',
      'dispatch_info': "Infos d'expédition",
      'dispatch_date': "Date d'expédition",
      'dispatch_status': "Statut d'expédition",
      'cargo_id': 'ID du colis',
      'cargo_info': 'Infos du colis',
      'registered': 'Enregistré',
      'sender': 'Expéditeur',
      'receiver': 'Destinataire',
      'quantity': 'Quantité',
      'payment_option': 'Option de paiement',
      'total_price': 'Prix total',
      'tracking_history': 'Historique de suivi',
      'status': 'Statut',
    },
  };

  /// Returns the localized value for the given key or the key itself.
  String translate(String key) {
    return _localizedValues[languageCode]?[key] ?? key;
  }
}
